import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ife's work",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <header 
          style = {{
            backgroundColor: "lightblue",
            padding: "2rem",
            fontSize: "30px",
            textAlign: "center",
            border: "2px solid black",
          }}
          >
          <p>This is a roughwork page</p>
        </header> */}
        
        {children}
        {/* <footer
          style = {{
            backgroundColor: "ghostwhite",
            padding: "2rem",
            fontSize: "15px",
            textAlign: "center",
          }}
          >
          <p>Call me or email me for more info: 07032727011/ @adeleyeifedayojoshua@gmail.com</p>
        </footer> */}
      </body>
    </html>
  );
}
