import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ife's work",
  description: "Generated by create next app",
};
export default function EventPlannerLayout ({children}:{
    children: React.ReactNode;
}) {
    return (
        <>
        {children}     
        </>       
    );
}
