import Image from "next/image"
import vendor from "/public/pic1c.svg"
import dashboard from "/public/calendar.svg"
import conversation from "/public/message.svg"
import transaction from "/public/money.svg"
import manageevents from "/public/3square.svg"
import notification from "/public/Notification.svg"
import arrow from "/public/ArrowrightUp.svg"
import search from "/public/search-normal.svg"
import photographer from "/public/pic1.svg"
import frame1 from "/public/frame1.svg"
import frame2 from "/public/Frame2.svg"
import makeup from "/public/pic2.svg"
import event1 from "/public/pic3.svg"
import catering from "/public/pic4.svg"
import musicdance from "/public/pic5.svg"
import event2 from "/public/pic6.svg"
import lp1 from "/public/pic1b.svg"
import ol1 from "/public/pic2b.svg"
import ol2 from "/public/pic3b.svg"
import lp2 from "/public/pic4b.svg"
import djm from "/public/pic1d.svg"
import dandan from "/public/pic2d.svg"
import djs from "/public/pic3d.svg"
import shasha from "/public/pic4d.svg"
import headset from "/public/pic1e.svg"

export const metadata  = {
  title: "Event-planner-dashboard",
  description: "Generated by create next app",
};
export default function EventDashboard(){
    return(
    <div className="flex w-full  min-h-screen flex-col p-6">
    <div className="flex flex-row w-full items-start justify-between bg-white-500">
      <ul className="mx-auto w-full md:border-black-500" id="item-list-1">
        <button className="ms-5 text-pink-600" id="span-item-5"><Image src={dashboard} alt="dashboard-icon" className="mx-2 float-left" priority/>Dashboard</button>
        <button className="ms-5"><Image src={conversation} alt="conversation-icon" className="mx-2 float-left" priority/>Conversation</button>
        <button className="ms-5"><Image src={transaction} alt="transaction-icon" className="mx-2 float-left" priority/>Transactions</button>
        <button className="ms-5"><Image src={manageevents} alt="manageevents-icon" className="mx-2 float-left" priority/>Manage events</button>
        <button className="ms-5 float-right mx-5" id="UA">UA</button>
        <button className="ms-5 float-right mx-5"> <Image src={notification} alt="notification-icon" className="mx-5 float-left" priority/>Switch to Vendor <Image src={arrow} alt="arrow-icon" className="mx-2 float-right" priority/></button>
      </ul>
    </div>
    <div  className="flex flex-row w-full items-start justify-between bg-white-500">
    <span className="mx-5 my-5 text-dark" id="span-item-1">Welcome, Adesanmi</span>
    <span className="float-right"  id="span-item-2"><Image src={search} alt="search-icon" className="mx-2 float-left" priority/>Search Vendors</span>
    </div>
    <div className="flex flex-row justify-around w-half bg-pink-100" id="item-wrapper-1">
      <p id="p-item-1">Find the Vendor for your next big thing here. Easy and Protected.</p>
      <div className="flex flex-row items-end justify-center">
      <Image src={frame1} alt="frame1-img" priority/>
      <Image src={frame2} alt="frame2-img" priority/>
      </div>
    </div>
    <div className="flex flex-row w-full items-start justify-between bg-white-500">
      <span id="span-item-3">Your Upcoming Event</span>
      <span className="text-pink-600 float-right" id="span-item-4">Manage Events</span>
    </div>
    <div className="flex flex-col w-full items-center justify-center bg-white-500 mt-5">
      <table>
        <tr>
          <td>Event name</td>
          <td>Date</td>
          <td>Description</td>
          <td>No of vendors</td>
          <td>Total cost</td>
        </tr>
        <tr>
          <td>Oduyemi wedding</td>
          <td> Dec 1,2023.</td>
          <td>Photography session for an upcoming wedding</td>
          <td>10 vendors services</td>
          <td>N200,000.00</td>
        </tr>
        <tr>
          <td>Goldnlilies Dec Party</td>
          <td>Dec 9,2023.</td>
          <td>Planning towards the december end of the year party</td>
          <td>4 vendors services</td>
          <td>N200,000.00</td>
        </tr>
      </table>
    </div>
    <div className="flex flex-row w-full items-start justify-between bg-white-500">
    <span id="span-item-6">Top Vendors Categories</span>
      <span className="text-pink-600 float-right" id="span-item-7">See all categories</span>
    </div>
    <div className="grid w-full" id="grid-container-1">
      <div className="relative flex items-center justify-center">
        <div className="absolute w-full h-full -z-10">
          <Image src={photographer} alt="photographer-img" className="w-full object-cover h-full" priority/>
          </div>Photographer</div>
      <div className="relative flex items-center justify-center"> <div className="absolute w-full h-full -z-10">
          <Image src={makeup} alt="makeup-img" className="w-full object-cover h-full" priority/>
          </div>Make-up Artist</div>
          <div className="relative flex items-center justify-center"> <div className="absolute w-full h-full -z-10">
          <Image src={event1} alt="event1-img" className="w-full object-cover h-full" priority/>
          </div>Event Planner</div>
          <div className="relative flex items-center justify-center"> <div className="absolute w-full h-full -z-10">
          <Image src={catering} alt="catering-img" className="w-full object-cover h-full" priority/>
          </div>Catering Services</div>
          <div className="relative flex items-center justify-center"> <div className="absolute w-full h-full -z-10">
          <Image src={musicdance} alt="m&d-img" className="w-full object-cover h-full" priority/>
          </div>Music & Dance</div>
          <div className="relative flex items-center justify-center"> <div className="absolute w-full h-full -z-10">
          <Image src={event2} alt="event2-img" className="w-full object-cover h-full" priority/>
          </div>Event Planner</div>
   </div>
   <div className="flex flex-row w-full items-start justify-between bg-white-500">
    <span id="span-item-8">Trending Photographer</span>
    </div>
    <div className="grid w-full" id="grid-container-2">
      <div className="flex flex-col">
      <div className="flex flex-row w-full items-center justify-center" id="item-image-1">
         <Image src={lp1} alt="lp1-img"className="w-full object-cover h-full" priority/></div>
      <div className="flex flex-col items-start">
        <ul id="item-list-2">
        <li>Lens Photography</li>
        <li>Lagos, Nigeria</li>
        <li>Price Range:<span className="text-green-600">N50k - N100k</span></li>
        </ul>
      </div>
      </div>
      <div className="flex flex-col">
      <div className="flex flex-row w-full items-center justify-center" id="item-image-1"><Image src={ol1} alt="ol1-img"className="w-full object-cover h-full" priority/></div>
      <div className="flex flex-col items-start">
        <ul id="item-list-2">
        <li>Octopus Lens</li>
        <li>Ondo, Nigeria</li>
        <li>Price Range:<span className="text-green-600">N80k - N100k</span> </li>
        </ul>
      </div>
      </div>
      <div className="flex flex-col">
      <div className="flex flex-row w-full items-center justify-center" id="item-image-1"><Image src={ol2} alt="ol2-img"className="w-full object-cover h-full" priority/></div>
      <div className="flex flex-col items-start">
        <ul id="item-list-2">
        <li>Octopus Lens</li>
        <li>Ondo, Nigeria</li>
        <li>Price Range: <span className="text-green-600">N80k - N100k</span></li>
        </ul>
      </div>
      </div>
      <div className="flex flex-col">
      <div className="flex flex-row w-full items-center justify-center" id="item-image-1"><Image src={lp2} alt="lp2-img"className="w-full object-cover h-full" priority/></div>
      <div className="flex flex-col items-start">
        <ul id="item-list-2">
        <li>Lens Photography</li>
        <li>Lagos, Nigeria</li>
        <li>Price Range:<span className="text-green-600">N50k - N100k</span></li>
        </ul>
      </div>
      </div>
   </div>
   <div className="flex flex-col w-half items-start justify-center" id="item-wrapper-2">
   <Image
       src={vendor}
        alt="vendor-frame"
         priority/>
      {/* <p id="p-item-2">Only an excellent Vendor deserves your attention. Make your next event more vibrant.</p> */}
    </div>
    <div className="flex flex-row w-full items-start justify-between bg-white-500">
    <span id="span-item-8">Trending Music & Dance</span>
    </div>
    <div className="grid w-full" id="grid-container-2">
      <div className="flex flex-col">
      <div className="flex flex-row w-full items-center justify-center" id="item-image-1"><Image src={djm} alt="djm-img"className="w-full object-contain h-full" priority/></div>
      <div className="flex flex-col items-start">
        <ul id="item-list-2">
        <li>DJ Mankan</li>
        <li>Lagos, Nigeria</li>
        <li>Price Range:<span className="text-green-600">N100k - N500k</span></li>
        </ul>
      </div>
      </div>
      <div className="flex flex-col">
      <div className="flex flex-row w-full items-center justify-center" id="item-image-1"><Image src={dandan} alt="dandan-img"className="w-full object-contain h-full" priority/></div>
      <div className="flex flex-col items-start">
        <ul id="item-list-2">
        <li>DanDan Dance</li>
        <li>Ondo, Nigeria</li>
        <li>Price Range:<span className="text-green-600">N80k - N150k</span> </li>
        </ul>
      </div>
      </div>
      <div className="flex flex-col">
      <div className="flex flex-row w-full items-center justify-center" id="item-image-1"><Image src={djs} alt="djs-img"className="w-full object-contain h-full" id="djs-img" priority/></div>
      <div className="flex flex-col items-start">
        <ul id="item-list-2">
        <li>DJ Splash</li>
        <li>Ondo, Nigeria</li>
        <li>Price Range:<span className="text-green-600">N70k - N100k</span></li>
        </ul>
      </div>
      </div>
      <div className="flex flex-col">
      <div className="flex flex-row w-full items-center justify-center" id="item-image-1"><Image src={shasha} alt="shasha-img"className="w-full object-contain h-full" priority/></div>
      <div className="flex flex-col items-start">
        <ul id="item-list-2">
        <li>Shasha Dance</li>
        <li>Lagos, Nigeria</li>
        <li>Price Range:<span className="text-green-600">N50k - N200k</span></li>
        </ul>
      </div>
      </div>
   </div>
   <div className="w-full">
      <p className="float-right"><Image src={headset} alt="headset-img"className="w-full h-full" priority/></p>
   </div>
    </div>
    );
}